#!/usr/bin/env python3
"""
Read the static site and produce an import bundle for WordPress.

Output: wp-theme/import/manifest.json plus one body file per page.
The bundle is rsynced to the server and consumed by import.php via
`wp eval-file`, which has the full WordPress API for meta, thumbnails,
sticky posts, and menus.
"""
import json, re, html, pathlib

SITE = pathlib.Path(__file__).resolve().parent.parent / "site"
OUT  = pathlib.Path(__file__).resolve().parent / "import"
(OUT / "pages").mkdir(parents=True, exist_ok=True)

PAGES = [
    # slug, menu label (None = not in main nav), template hint
    ("food", "Food"), ("furniture", "Furniture"), ("programs", "Programs"),
    ("news", "News"), ("get-involved", "Get involved"), ("about", "About"),
    ("gallery", "Gallery"), ("faq", "FAQ"), ("contact", "Contact"),
    ("donate", None), ("tech-for-teens", None), ("damien-center", None),
    ("chaplaincy", None), ("mlk-scholarship", None), ("community-center", None),
]

# Text that should come from the TAUM Info panel instead of being baked in.
SHORTCODES = [
    ("Monday evenings at 5:45", "[taum meal_monday]"),
    ("Thursdays at noon", "[taum meal_thursday]"),
    ("Monday 5:45 pm", "[taum meal_monday_short]"),
    ("Thursday noon", "[taum meal_thursday_short]"),
    ("(518) 274-5920", "[taum phone]"),
    ("lmalatesta@taum.org", "[taum email_office]"),
    ("nortonlevering@taum.org", "[taum email_director]"),
]

def rel_links(s: str) -> str:
    s = re.sub(r'href="([a-z0-9-]+)\.html(#[a-z0-9-]+)?"', r'href="/\1/\2"', s)
    s = s.replace('href="/index/"', 'href="/"')
    s = re.sub(r'src="(images/[^"]+)"', r'src="{{THEME}}/assets/\1"', s)
    s = s.replace('src="mural-photo.jpg"', 'src="{{THEME}}/assets/images/mural-photo.jpg"')
    return s

def apply_shortcodes(s: str) -> str:
    # Don't replace inside href/mailto/tel attributes; only in text.
    parts = re.split(r'(<[^>]+>)', s)
    for i, p in enumerate(parts):
        if p.startswith("<"):
            continue
        for lit, sc in SHORTCODES:
            p = p.replace(lit, sc)
        parts[i] = p
    return "".join(parts)

def strip_editor_notes(s: str) -> str:
    return re.sub(r"<!--\s*── EDITOR'S NOTE.*?-->", "", s, flags=re.S)

manifest = {"pages": [], "events": [], "partners": [], "posts": [], "menu": []}

for slug, label in PAGES:
    src = (SITE / f"{slug}.html").read_text(encoding="utf-8")
    main = re.search(r"<main id=\"main\">(.*?)</main>", src, re.S).group(1)
    hero = re.search(r'<div class="(?:page-hero|faq-hero)([^"]*)">(.*?)</div>\s*</div>\s*</div>|<div class="(?:page-hero|faq-hero)([^"]*)">(.*?)</div>\s*</div>', main, re.S)
    # Robust hero extraction: find the first page-hero/faq-hero block by balancing divs.
    m = re.search(r'<div class="(page-hero|faq-hero)([^"]*)">', main)
    start = m.start()
    depth = 0; i = m.end(); hero_end = None
    depth = 1
    for tag in re.finditer(r"<div\b|</div>", main[m.end():]):
        depth += 1 if tag.group(0).startswith("<div") else -1
        if depth == 0:
            hero_end = m.end() + tag.end()
            break
    hero_html = main[start:hero_end]
    body_html = main[hero_end:]

    style  = (m.group(2) or "").strip()
    kicker = re.search(r'<p class="kicker">(.*?)</p>', hero_html, re.S)
    h1     = re.search(r"<h1>(.*?)</h1>", hero_html, re.S)
    lede   = re.search(r'<p class="lede"[^>]*>(.*?)</p>', hero_html, re.S) or re.search(r'<p style="max-width:38em[^"]*">(.*?)</p>', hero_html, re.S)
    photo  = re.search(r'<img src="([^"]+)"[^>]*alt="([^"]*)"', hero_html)
    actions= re.search(r'<div class="actions"[^>]*>(.*?)</div>', hero_html, re.S)

    title = html.unescape(re.sub(r"<[^>]+>", "", h1.group(1))).strip()
    # If the hero carried buttons, keep them at the top of the body so nothing is lost.
    if actions:
        body_html = f'<p class="hero-actions">{rel_links(actions.group(1)).strip()}</p>\n' + body_html

    body = strip_editor_notes(body_html)
    # The About page's partners section is generated by page-about.php from the Partners post type.
    if slug == "about":
        body = re.sub(r'<section id="partners">.*?</section>\s*', "", body, flags=re.S)
    # The gallery becomes a native gallery block; capture the images for the importer.
    gallery_items = []
    if slug == "gallery":
        for gm in re.finditer(r'<img src="([^"]+)" alt="([^"]*)"><span class="cap">(.*?)</span>', body):
            gallery_items.append({"src": gm.group(1), "alt": html.unescape(gm.group(2)), "caption": html.unescape(gm.group(3))})
        body = re.sub(r'<div class="gallery-grid">.*?</div>\s*(?=<div class="callout")', "{{GALLERY}}\n\n  ", body, flags=re.S)
    body = rel_links(body)
    body = apply_shortcodes(body)
    # Body pages have a <section><div class="wrap"> wrapper; page.php supplies that. Unwrap the FIRST one only.
    body = re.sub(r'^\s*<section>\s*<div class="wrap[^"]*">', "", body, count=1)
    body = re.sub(r'</div>\s*</section>\s*$', "", body.rstrip(), count=1)
    body = body.strip() + "\n"

    (OUT / "pages" / f"{slug}.html").write_text(body, encoding="utf-8")
    manifest["pages"].append({
        "slug": slug,
        "title": title,
        "kicker": html.unescape(re.sub(r"<[^>]+>", "", kicker.group(1))).strip() if kicker else "",
        "excerpt": apply_shortcodes(rel_links(lede.group(1))).strip() if lede else "",
        "hero_style": style,
        "photo": photo.group(1) if photo else "",
        "photo_alt": html.unescape(photo.group(2)) if photo else "",
        "menu_label": label,
        "gallery": gallery_items,
        "empty_body": slug == "news",  # page-news.php generates everything
    })
    if label:
        manifest["menu"].append({"label": label, "slug": slug})

# Homepage as a static front page (front-page.php renders it; the page just needs to exist).
manifest["pages"].insert(0, {"slug": "home", "title": "Home", "kicker": "", "excerpt": "", "hero_style": "", "photo": "mural-photo.jpg", "photo_alt": "The TAUM building on Second Street in Troy, with a bright mural of birds building a nest together.", "menu_label": None, "front": True})
(OUT / "pages" / "home.html").write_text("", encoding="utf-8")

# Events. Weekly ones are the meals; one-time ones are the yearly gatherings.
manifest["events"] = [
    {"title": "Community meal", "recurring": "weekly", "day": "Mon", "time": "5:45 pm", "place": "392 Second Street",
     "content": "A hot dinner and a seat at a full table. Everyone is welcome, whatever brought you here.", "order": 1},
    {"title": "Community meal & groceries", "recurring": "weekly", "day": "Thu", "time": "Noon", "place": "392 Second Street",
     "content": "Lunch at noon, with groceries going out the same day. Bring a bag if you have one, and we'll help you carry it if you don't.", "order": 2},
    {"title": "The Free Food Fridge", "recurring": "weekly", "day": "24/7", "time": "Any hour", "place": "outside our front door",
     "content": "Fresh produce, dairy, and prepared meals, out on the sidewalk day and night. Take what you need.",
     "url": "/food/", "url_label": "More about food at TAUM", "order": 3},
    {"title": "CROP Hunger Walk", "date": "2027-05-02", "time": "First Sunday in May", "place": "Troy",
     "content": "Our biggest walk of the year, raising money to fight hunger here in Troy and around the world. Bring the family, bring the dog, bring a team from your congregation or workplace.",
     "url": "/contact/", "url_label": "Ask about walking with us"},
    {"title": "FEAST! Dining for a Cause", "date": "", "time": "Date to be announced", "place": "",
     "content": "An evening of good food and good company that keeps our food programs running all year. Local restaurants donate the meal; every ticket goes straight to the table on Second Street.",
     "url": "https://secure.lglforms.com/form_engine/s/zmQHJr8EUVLsa5i9JZzIrw", "url_label": "Get notified when tickets open"},
    {"title": "Forty Flames for Forty Years", "date": "2026-12-31", "time": "Now through December", "place": "our 40th anniversary",
     "content": "Forty years of neighbors feeding neighbors. Light a flame in honor of someone who made Troy better, and help us carry the next forty.",
     "url": "https://docs.google.com/forms/d/e/1FAIpQLSc3lvfd-69c7KV95N8lchVQaoVPV_EZ4qFsUpPTWqsr_oxoLA/viewform", "url_label": "Light a flame"},
]

manifest["partners"] = [
    {"title": "Rensselaer County Summer Youth Employment Program", "tier": "Program partners", "url": "https://www.rensco.com/406/Youth"},
    {"title": "Russell Sage College", "tier": "Program partners"},
    {"title": "Community Compass", "tier": "Program partners"},
    {"title": "Our founding and member congregations", "tier": "Program partners"},
]

manifest["posts"] = [
    {"title": "Growing and serving: help our garden grow", "sticky": True, "date": "2026-09-01 09:00:00",
     "excerpt": "With partners at Mohawk Global and Capital Roots, and generous gifts from the First Reformed Church of Schenectady and the Common Roots Foundation, we're expanding our community garden in 2026. Fresh vegetables grown here go straight to our meal program and Free Food Fridge.",
     "content": "<p>With partners at Mohawk Global and Capital Roots, and generous gifts from the First Reformed Church of Schenectady and the Common Roots Foundation, we're expanding our community garden in 2026. Fresh vegetables grown here go straight to our meal program and Free Food Fridge.</p><p>Tomatoes, peppers, and greens from our beds behind the building are going straight onto the Thursday table and into the Free Food Fridge. If you want dirt under your fingernails, the garden crew could use you.</p><p><a class=\"btn small\" href=\"https://secure.lglforms.com/form_engine/s/Kr1X6bDWzYn2WsP_7ufiYw\">Support the garden</a> <a class=\"btn small ghost\" href=\"/get-involved/\">Join the garden crew</a></p>",
     "photo": "images/garden-harvest.jpg"},
    {"title": "Forty years of neighbors feeding neighbors", "sticky": True, "date": "2026-01-15 09:00:00",
     "excerpt": "TAUM turns forty this year. What started in 1986 as a handful of Troy congregations pooling their community work is now a neighborhood center that serves thousands of people a year.",
     "content": "<p>TAUM turns forty this year. What started in 1986 as a handful of Troy congregations pooling their community work is now a neighborhood center that serves thousands of people a year. We're marking it all year with Forty Flames for Forty Years.</p><p>We're looking for forty friends (people, families, congregations, businesses) to each \"light a candle\" by hosting something for the community: a dinner party, a movie night, a garden build, an ice cream social, a fresh coat of paint on a wall that needs it.</p><p><a class=\"btn small\" href=\"https://docs.google.com/forms/d/e/1FAIpQLSc3lvfd-69c7KV95N8lchVQaoVPV_EZ4qFsUpPTWqsr_oxoLA/viewform\">Light a flame</a> <a class=\"btn small ghost\" href=\"/about/\">Read our story</a></p>",
     "photo": "images/hands-unity.jpg"},
]

(OUT / "manifest.json").write_text(json.dumps(manifest, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"pages: {len(manifest['pages'])}  events: {len(manifest['events'])}  partners: {len(manifest['partners'])}  posts: {len(manifest['posts'])}  menu: {len(manifest['menu'])}")
for p in manifest["pages"]:
    print(f"  {p['slug']:18} {p['title'][:44]:46} style={p['hero_style'] or '-':13} photo={'yes' if p['photo'] else 'no'}")
